### ISSUE TITLE
ValueError: No pressure specified to pressure-dependent PDepArrhenius.getRateCoefficient()

### ISSUE THREAD

**Issue by kblondal** [cfgoldsmith/RMG-Py#61] opened 2019-02-21 01:52 UTC
I get the error message in the link below if I try to include NOx2018 as a reaction library for methane catalytic combustion.

https://github.com/kblondal/RMG-Py/blob/cat_testing/cat_inputfiles/methane_catcombust_190220_2/errormsg.txt 

It seems that this is caused by for example reaction index 24 in NOx2018 which is kinetics = PDepArrhenius(...

Is there a way for me to specify the pressure (such as just using the initial pressure) for these types of reactions?

**Comment by rwest** [comment] 2019-02-21 01:59
The good news is that it looks like the error occurred in the call to `rmgpy.reaction.Reaction.check_collision_limit_violation` which I think only happens at the very end of the model generation, so you can assume your model is final, while we work on fixing the bug.

**Comment by rwest** [comment] 2019-02-21 05:09
I can't think why the cat modifications would have caused this. Could you try to reproduce it without any catalysis (maybe an input file with just the species needed to make that reaction show up, and your T,P)  and see if it happens on master? (and if so, submit an issue to the main RMG tracker?)

**Comment by kblondal** [comment] 2019-02-25 19:50
I reproduced it as you suggested without surface chemistry and switching from surfaceReactor to simpleReactor to be able to run it on master. See input file [here](https://github.com/kblondal/RMG-Py/blob/cat_testing/cat_inputfiles/190225_methane_nocat/input.py).

The error did not occur in this case despite PDepArrhenius reactions being included in the final mechanism. See end message [here](https://github.com/kblondal/RMG-Py/blob/cat_testing/cat_inputfiles/190225_methane_nocat/completemsg.txt). The final mechanism is also in the same folder.

**Comment by rwest** [comment] 2019-06-19 14:06
This issue is now at https://github.com/ReactionMechanismGenerator/RMG-Py/issues/1635 with additional details so I'm closing this report.

**Closed as completed by rwest** 2019-06-19 14:06 UTC
